# Use official Golang image
FROM golang:1.20

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Build the application
RUN go mod init logservice && go mod tidy && go build -o logservice main.go

# Run the application
CMD ["./logservice"]
